on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker compose down --remove-orphans
          docker compose up --build --wait -d
