on:
  push:
    branches:
      - main

jobs:
  generate_env_file:
    runs-on: self-hosted
    name: Deploy
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Generate env file
        run: |
          cp .env.example .env
      - name: Restart docker compose
        run: |
          docker compose down --remove-orphans
          docker compose up --build --wait -d
      - name: Build styles
        run: |
          docker exec -it gus-php-1 sh -c "npm run build"
